CREATE TABLE IF NOT EXISTS Complaints(
   ComplaintId INTEGER PRIMARY KEY AUTOINCREMENT,
   UserId INTEGER NOT NULL,
   Reason NVARCHAR(100) NOT NULL,
   Details NVARCHAR(500) NOT NULL,
   ComplaintDate DATETIME NOT NULL,
   Response NVARCHAR(500),

   FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS IFK_ComplaintsUserId ON Complaints (UserId);